# Generated by Django 3.2.7 on 2023-04-11 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
                   INSERT INTO menu_menu (id, name) 
                       VALUES (1, 'main menu');

                   INSERT INTO menu_menulistitem (id, name, menu_id, parent_id, path) 
                       VALUES (1, 'главная', 1, null, '/main');
                   INSERT INTO menu_menulistitem (id, name, menu_id, parent_id, path) 
                       VALUES (2, 'о нас', 1,null, '/about');
                   INSERT INTO menu_menulistitem (id, name, menu_id, parent_id, path) 
                       VALUES (3, 'наша история', 1,2, '/about/history');
                    INSERT INTO menu_menulistitem (id, name, menu_id, parent_id, path) 
                       VALUES (4, 'услуги', 1,2, '/about/services');
                    INSERT INTO menu_menulistitem (id, name, menu_id, parent_id, path) 
                       VALUES (5, 'наши контакты', 1,2, '/about/contacts');
                    INSERT INTO menu_menulistitem (id, name, menu_id, parent_id, path) 
                       VALUES (6, 'цены', 1,null, '/prices');
                    INSERT INTO menu_menulistitem (id, name, menu_id, parent_id, path) 
                       VALUES (7, 'акции', 1,6, 'prices/promotion');
                    INSERT INTO menu_menulistitem (id, name, menu_id, parent_id, path) 
                       VALUES (8, 'скидки', 1,6, '/prices/sales');
                    INSERT INTO menu_menulistitem (id, name, menu_id, parent_id, path) 
                       VALUES (9, 'студентам', 1,8, '/prices/sales/for-students');
                    INSERT INTO menu_menulistitem (id, name, menu_id, parent_id, path) 
                       VALUES (10, 'пенсионерам', 1,8, '/prices/sales/for-pensioners');
                    INSERT INTO menu_menulistitem (id, name, menu_id, parent_id, path) 
                       VALUES (11, 'партнеры', 1,null, '/partners');
                    INSERT INTO menu_menulistitem (id, name, menu_id, parent_id, path) 
                       VALUES (12, 'звонок', 1,4, 'https://web.whatsapp.com');
                    INSERT INTO menu_menulistitem (id, name, menu_id, parent_id, path) 
                       VALUES (13, 'instagram', 1,5, 'https://www.instagram.com/');
                    INSERT INTO menu_menulistitem (id, name, menu_id, parent_id, path) 
                       VALUES (14, 'whatsapp', 1,5, 'https://web.whatsapp.com/');
               """)
    ]
