# Generated by Django 3.2.7 on 2023-04-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230411_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulistitem',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
